#! /usr/bin/python3.9

from .exceptions import CATIAApplicationException

__all__ = ["CATIAApplicationException"]
